version: '3.8'

volumes:
  maria:

services:

  # container PHP
  airbebphp:
    container_name: phpairbeb
    build: 
      context: ./php
    ports:
      - '9000:9000'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - airbebbase

  # container nginx
  airbebnginx:
    container_name: nginxairbeb
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - airbebphp
      - airbebbase
      - airbebnode

  # container de bdd en MARIADB
  airbebbase:
    container_name: baseairbeb
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: admin2024
      MYSQL_DATABASE: airbebdata
      MYSQL_USER: airbebuser
      MYSQL_PASSWORD: airbeb2024
    ports:
      - '3307:3306'
    volumes:
      - maria:/var/lib/mysql

  # container NODEJS
  airbebnode:
    container_name: nodeairbeb
    build: 
      context: ./node
    volumes:
      - ./app:/var/www/symfo
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - airbebphp
    tty: true
