INSERT INTO annonce (type_id,title,description,countryname,cityname,streetname,image_path,image_slug,prix,nombre_couchage,nombre_piece,taille,user_id) VALUES
	 (1,'Pebble Lodge','Pebble Lodge est une maison élégante, moderne et de luxe de la maison pour quatre personnes (plus un bébé). Situé sur le parc de vacances cinq étoiles Chesil Beach, Pebble Lodge offre une vue imprenable sur le Lagon de la Fleet et la plage de Chesil, une partie célèbre de la côte jurassique.','France','Perpignan','50 Rue Georges Franju, Suite','logement-entier-weymouth-royaume-uni-65b77afd0ec21804923577.webp' ,NULL,56,2,2,250,1),
	 (1,'Olive Tree House','Située au milieu des oliviers dans un endroit isolé, calme et paisible, Olive Tree House est un trou unique en chêne et romantique avec une vue imprenable sur la campagne. Le village de Ripe est accessible à pied et la ville historique de Lewes et la côte du Sussex sont toutes deux à seulement 20 à 2 minutes en voiture.','Royaume-Uni','Ripe','wilderness','Olive Tree House-65b3c56239a44.webp',NULL,344,1,1,150,1),
	 (1,'Cob Cottage','Partez à la recherche d''une pause dans cette maison organique unique en son genre. Ce lieu de retraite confortable a été sculpté à la main dans des matériaux naturels locaux et durables et dispose d''un espace de vie central avec des escaliers coulés dans une dalle en porte-à-faux menant à la chambre loft.','Canada','Mayne Island','Horton Bay Rd','Cob Cottage-65b7693f18bf6.webp',NULL,137,2,1,70,2),
	 (1,'Chalet & terrasse sur piste de Ski','Situé à 1200m d''Altitude, dans le hameau de Belleface, notre Chalet est en pleine nature sur la mythique piste de ski Kandhar qui accueille la coupe du monde de ski alpin. Sans vis-à-vis, avec une terrasse de 40m2, vous apprécierez la quiétude du lieu et la vue spectaculaire sur la chaîne du Mont Blanc, l''Aiguille du Midi et la vallée de Chamonix.
Nous avons aménagé le bas de chalet avec goût et tout le confort nécessaire pour que vous passiez un agréable séjour que ce soit en été ou en hiver.','France','Les Houches','Rte du col de Voza','les-houches-65b76a13ce9f264033569.webp',NULL,121,3,2,125,2),
	 (1,'BALIAN TREEHOUSE w beautiful pool','La cabane dans les arbres de Balian est à seulement 3 minutes à pied de la plage. Depuis la véranda, vous pouvez regarder le lever du soleil le matin, et profiter de la vue sur notre magnifique jardin (900 m2) avec piscine. (une fois entièrement réservée, voir également','Indonésie','Balian Beach','JL Pantai Balian','bamlianbeach-65b7778412665.webp',NULL,85,1,1,85,3),
	 (1,'IM PFERDESTALL','L''espace a des plafonds bas et de petites fenêtres à meneaux. L''espace est adapté aux personnes à la recherche d''une retraite plus spacieuse et confortable. Grâce au poêle et au sol froid non sous-sol, l''appartement ne convient pas aux tout-petits qui rampent encore au sol.','Allemagne','Löhnberg','L244','werballenamge-65b7784be10b9.webp',NULL,97,2,1,140,2),
	 (1,'Poole Harbour','Cette spacieuse propriété contemporaine à Poole Dorset a tout ce dont votre famille et vos amis ont besoin pour un excellent séjour,peut accueillir 12 personnes, un emplacement idéal pour les villes et la vue, la plage et le parc de l''autre côté de la route,
plus de 200 commentaires 5 étoiles. Chargeur EV payable séparément 0,70 par Kw.
Kayaks et vélos compris Jacuzzi et sauna en option, prix sur demande.
Certainement pas une maison pour les fêtes,
Politique de calme stricte après 22h, seules les familles sont autorisées.','Royaume-uni','Poole','Lulworth Avenue','portdepoole-65b77d3e5aba4.webp',NULL,421,5,2,350,2),
	 (1,'annonceur01','ceci est la première annonce crée par un Role Annonceur.','DAKARA','Type:planet','17 Rue des beaux arts','dakara-65b8af0984ae4.jpg',NULL,15000,999,999,9999,3),
	 (1,'Prométhée X-23','Le Prométhée (BC-23) était un croiseur spatial construit par la Terre, pour le compte de l''US Air Force et placé sous l''autorité du Commandement de la défense terrienne, dans le but de faire face aux vaisseaux-mères goa''ulds de classe Ha''tak.','BC-23','Croiseur de classe','Type interstellaire','bc-23-65b8c1e57033d.jpg',NULL,90000,120,150,400,2);
